/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadImageRouteImport } from './routes/api.upload-image'
import { Route as AuthedTeachersRouteImport } from './routes/_authed/teachers'
import { Route as AuthedStudentsRouteImport } from './routes/_authed/students'
import { Route as AuthedInvitationsRouteImport } from './routes/_authed/invitations'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCoursesRouteImport } from './routes/_authed/courses'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedAssignmentsIndexRouteImport } from './routes/_authed/assignments/index'
import { Route as AuthedStudentsStudentIdRouteImport } from './routes/_authed/students.$studentId'
import { Route as AuthedLessonsLessonIdRouteImport } from './routes/_authed/lessons.$lessonId'
import { Route as AuthedCoursesCourseIdRouteImport } from './routes/_authed/courses.$courseId'
import { Route as AuthedAssignmentsAssignmentIdRouteImport } from './routes/_authed/assignments/$assignmentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeachersRoute = AuthedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudentsRoute = AuthedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvitationsRoute = AuthedInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCoursesRoute = AuthedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssignmentsIndexRoute = AuthedAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStudentsStudentIdRoute = AuthedStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AuthedStudentsRoute,
} as any)
const AuthedLessonsLessonIdRoute = AuthedLessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCoursesCourseIdRoute = AuthedCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AuthedCoursesRoute,
} as any)
const AuthedAssignmentsAssignmentIdRoute =
  AuthedAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthedCalendarRoute
  '/courses': typeof AuthedCoursesRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/invitations': typeof AuthedInvitationsRoute
  '/students': typeof AuthedStudentsRouteWithChildren
  '/teachers': typeof AuthedTeachersRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/assignments/$assignmentId': typeof AuthedAssignmentsAssignmentIdRoute
  '/courses/$courseId': typeof AuthedCoursesCourseIdRoute
  '/lessons/$lessonId': typeof AuthedLessonsLessonIdRoute
  '/students/$studentId': typeof AuthedStudentsStudentIdRoute
  '/assignments/': typeof AuthedAssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthedCalendarRoute
  '/courses': typeof AuthedCoursesRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/invitations': typeof AuthedInvitationsRoute
  '/students': typeof AuthedStudentsRouteWithChildren
  '/teachers': typeof AuthedTeachersRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/assignments/$assignmentId': typeof AuthedAssignmentsAssignmentIdRoute
  '/courses/$courseId': typeof AuthedCoursesCourseIdRoute
  '/lessons/$lessonId': typeof AuthedLessonsLessonIdRoute
  '/students/$studentId': typeof AuthedStudentsStudentIdRoute
  '/assignments': typeof AuthedAssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/courses': typeof AuthedCoursesRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/invitations': typeof AuthedInvitationsRoute
  '/_authed/students': typeof AuthedStudentsRouteWithChildren
  '/_authed/teachers': typeof AuthedTeachersRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/_authed/assignments/$assignmentId': typeof AuthedAssignmentsAssignmentIdRoute
  '/_authed/courses/$courseId': typeof AuthedCoursesCourseIdRoute
  '/_authed/lessons/$lessonId': typeof AuthedLessonsLessonIdRoute
  '/_authed/students/$studentId': typeof AuthedStudentsStudentIdRoute
  '/_authed/assignments/': typeof AuthedAssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/calendar'
    | '/courses'
    | '/dashboard'
    | '/invitations'
    | '/students'
    | '/teachers'
    | '/api/upload-image'
    | '/assignments/$assignmentId'
    | '/courses/$courseId'
    | '/lessons/$lessonId'
    | '/students/$studentId'
    | '/assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/calendar'
    | '/courses'
    | '/dashboard'
    | '/invitations'
    | '/students'
    | '/teachers'
    | '/api/upload-image'
    | '/assignments/$assignmentId'
    | '/courses/$courseId'
    | '/lessons/$lessonId'
    | '/students/$studentId'
    | '/assignments'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/calendar'
    | '/_authed/courses'
    | '/_authed/dashboard'
    | '/_authed/invitations'
    | '/_authed/students'
    | '/_authed/teachers'
    | '/api/upload-image'
    | '/_authed/assignments/$assignmentId'
    | '/_authed/courses/$courseId'
    | '/_authed/lessons/$lessonId'
    | '/_authed/students/$studentId'
    | '/_authed/assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teachers': {
      id: '/_authed/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthedTeachersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/students': {
      id: '/_authed/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthedStudentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invitations': {
      id: '/_authed/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthedInvitationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/courses': {
      id: '/_authed/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthedCoursesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assignments/': {
      id: '/_authed/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AuthedAssignmentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/students/$studentId': {
      id: '/_authed/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthedStudentsStudentIdRouteImport
      parentRoute: typeof AuthedStudentsRoute
    }
    '/_authed/lessons/$lessonId': {
      id: '/_authed/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AuthedLessonsLessonIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/courses/$courseId': {
      id: '/_authed/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthedCoursesCourseIdRouteImport
      parentRoute: typeof AuthedCoursesRoute
    }
    '/_authed/assignments/$assignmentId': {
      id: '/_authed/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AuthedAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedCoursesRouteChildren {
  AuthedCoursesCourseIdRoute: typeof AuthedCoursesCourseIdRoute
}

const AuthedCoursesRouteChildren: AuthedCoursesRouteChildren = {
  AuthedCoursesCourseIdRoute: AuthedCoursesCourseIdRoute,
}

const AuthedCoursesRouteWithChildren = AuthedCoursesRoute._addFileChildren(
  AuthedCoursesRouteChildren,
)

interface AuthedStudentsRouteChildren {
  AuthedStudentsStudentIdRoute: typeof AuthedStudentsStudentIdRoute
}

const AuthedStudentsRouteChildren: AuthedStudentsRouteChildren = {
  AuthedStudentsStudentIdRoute: AuthedStudentsStudentIdRoute,
}

const AuthedStudentsRouteWithChildren = AuthedStudentsRoute._addFileChildren(
  AuthedStudentsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedCoursesRoute: typeof AuthedCoursesRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInvitationsRoute: typeof AuthedInvitationsRoute
  AuthedStudentsRoute: typeof AuthedStudentsRouteWithChildren
  AuthedTeachersRoute: typeof AuthedTeachersRoute
  AuthedAssignmentsAssignmentIdRoute: typeof AuthedAssignmentsAssignmentIdRoute
  AuthedLessonsLessonIdRoute: typeof AuthedLessonsLessonIdRoute
  AuthedAssignmentsIndexRoute: typeof AuthedAssignmentsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedCoursesRoute: AuthedCoursesRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInvitationsRoute: AuthedInvitationsRoute,
  AuthedStudentsRoute: AuthedStudentsRouteWithChildren,
  AuthedTeachersRoute: AuthedTeachersRoute,
  AuthedAssignmentsAssignmentIdRoute: AuthedAssignmentsAssignmentIdRoute,
  AuthedLessonsLessonIdRoute: AuthedLessonsLessonIdRoute,
  AuthedAssignmentsIndexRoute: AuthedAssignmentsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
